apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  labels:
    app: ping-pong-app
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
