apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- ../../base
- todo-backup-cronjob.yaml

patches:
- path: patch-todo-postgres-pgdata.yaml

images:
- name: broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/broadcaster
  newTag: main-524863da9a7d2443b528c977d5eb01d804d0baf6
- name: todo-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/todo-app
  newTag: main-524863da9a7d2443b528c977d5eb01d804d0baf6
- name: todo-backend-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/todo-backend
  newTag: main-524863da9a7d2443b528c977d5eb01d804d0baf6
- name: todo-backup
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/todo-backup
  newTag: "1.0"
- name: todo-cron
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/todo-cron
  newTag: main-524863da9a7d2443b528c977d5eb01d804d0baf6
