apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - todo-app-configmap.yaml
  - todo-app-deployment.yaml
  - todo-app-service.yaml
  - todo-app-pvc.yaml
  - todo-app-ingress.yaml
  - todo-backend-configmap.yaml
  - todo-backend-secret.yaml
  - todo-backend-deployment.yaml
  - todo-backend-service.yaml
  - todo-postgres.yaml
  - todo-cron-cronjob.yaml
