apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cron
  labels:
    app: todo-cron
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: todo-cron
        spec:
          restartPolicy: OnFailure
          containers:
            - name: todo-cron
              image: todo-cron
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 25m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
