apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-app
  labels:
    app: todo-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend-app
  template:
    metadata:
      labels:
        app: todo-backend-app
    spec:
      containers:
        - name: todo-backend-app
          image: todo-backend-app
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: todo-backend-config
            - secretRef:
                name: postgres-secret
