apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-log-volume
          persistentVolumeClaim:
            claimName: todo-app-pvc
      containers:
        - name: todo-app
          image: todo-app
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-log-volume
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: todo-app-config
