apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
data:
  information.txt: |
    This is the "Log output" application from the DevOps with Kubernetes course.
  MESSAGE: "Hello from the ConfigMap"
