apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- volume.yaml
- gateway.yaml
- httproute.yaml

images:
- name: log-output-reader
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/log-output-reader
  newTag: b7b4a12cb8a7378c0cb93dd603097561a35058f6
- name: log-output-writer
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/log-output-writer
  newTag: b7b4a12cb8a7378c0cb93dd603097561a35058f6
