apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-app
  labels:
    app: todo-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend-app
  template:
    metadata:
      labels:
        app: todo-backend-app
    spec:
      containers:
        - name: todo-backend-app
          image: todo-backend-app:1.3
          imagePullPolicy: Never

          env:
            - name: PORT
              value: "3000"