apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: patch-todo-postgres-pgdata.yaml
- path: patch-broadcaster-log-only.yaml

images:
- name: broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/broadcaster
  newTag: main-a3fa041ce5e97f0940f1a363fe99f7ebfa56fa15
- name: todo-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/todo-app
  newTag: main-a3fa041ce5e97f0940f1a363fe99f7ebfa56fa15
- name: todo-backend-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/todo-backend
  newTag: main-a3fa041ce5e97f0940f1a363fe99f7ebfa56fa15
- name: todo-cron
  newName: europe-north1-docker.pkg.dev/dwk-gke-502909/dwk-repo/todo-cron
  newTag: main-a3fa041ce5e97f0940f1a363fe99f7ebfa56fa15
